### ISSUE TITLE
Git pull unsuccessful

### ISSUE THREAD

**Issue by bryangators** [jon3882/mealPlanner#20]
When creating a pdf image on local server it pushed changes to git hub causing the pull from the server to be unsuccessful. I had to stash the files first before I was able to pull the changes from git hub.

**Comment by jon3882** [comment]
I was able to successfully push my changes doing the following:

1. stage all changes
2. Commit all changes (except plan.pdf and plan.png)
3. abort merge
4. fetch 
5. local merge

The last two steps can be accomplished with a pull.
