### ISSUE TITLE
Meal planner table switching foods

### ISSUE THREAD

**Issue by bryangators** [jon3882/mealPlanner#27]
When saving foods the meal planner seems to switch the order of the foods each time it saves in every cell.

Example(numbers are food elements):
1...2...3... after saving will appear in the table 3...2...1... seems to do this in every cell.

Also when editing a current meal that has 1...2..., if you add another food that food item will be displayed first on the list until it is switched the next time the planner is changed.

**Comment by jon3882** [comment]
When I changed the way the meal planner meals were saved and created to
make them dynamic the elements are rewritten in varying patterns back into
the array.  I guess I didn't think the order of the foods in the cell was
very important, so I didn't look into fixing the issue.  I can look at it
after I finish the context menu.

**Comment by jon3882** [comment]
Issue fixed in committ [5997e14...](https://github.com/jon3882/mealPlanner/commit/5997e14c5ecc32a734a8d722e49d8e7771f33a0b)
